#+TITLE: AboutScripts
#+AUTHOR: Haider Mirza

* Table of contents: :toc:
- [[#who-am-i][Who am I?]]

* Who am I?
#+begin_src
  _   _ __  ___
 | | | |  \/  |
 | |_| | |\/| | My Github: https://github.com/Ha1derMirza
 |  _  | |  | | My Matrix: @haider.mirza:matrix.org
 |_| |_|_|  |_|
#+end_src
My Name is Haider Mirza and I am a 3D artist and Programmer.
All my projects are hosted on github and are free and open-source.
Most of my projects are licensed under GPL V3 license.
* NOTE:
  I have switched to GNU Guix so this script is depricated.
  
* What is ArchInstall
ArchInstall is a pre-installation script for ArchLinux that I had composed in Bash. This Script installs all of my config to your system. The proccess Is fully Automatic and may require your sudo password.

** NOTE
This script is not allowed to be run as root. You will be asked to enter your Sudo password at various points during this installation. This is to give PACMAN the necessary permissions to install the software. So stay near your computer.
